version: "3.8"
services:
  web:
    build: .
    command: bash -c "entrypoint.sh && bash init.sh"
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
        - '5432:5432' 
    volumes:
        - db:/var/lib/postgresql/data
volumes:
  db:
      driver: local